spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce
spring.data.redis.host=redis
spring.kafka.bootstrap-servers=kafka:29092

management.server.port=8080
management.endpoints.web.exposure.include=health