spring.application.name=sb-ecom

#spring.profiles.active=local

# ===============================
# ========== DATABASE ==========
# ===============================

spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC';
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG

project.image=images/

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom

frontend.url=http://localhost:5173/
image.base.url=http://localhost:8080/images

stripe.secret.key=${STRIPE_SECRET_KEY}

spring.jpa.open-in-view=false
logging.level.root=INFO


# ===============================
# ========== ACTUATOR ==========
# ===============================

management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.health.db.enabled=true
management.health.diskspace.enabled=true
management.health.redis.enabled=true

management.server.port=8080


# ===============================
# ========== REDIS ==========
# ===============================

spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000

spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false


# ===============================
# ========== KAFKA ==========
# ===============================

spring.kafka.bootstrap-servers=kafka:29092

# ---- PRODUCER ----
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# ---- CONSUMER ----
spring.kafka.consumer.group-id=sb-ecom-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ---- LISTENER ----
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.listener.concurrency=3


# ===============================
# ========== KAFKA TOPICS ==========
# ===============================

kafka.topic.order-created=order.created
kafka.topic.payment-success=payment.success
kafka.topic.inventory-update=inventory.update


app.bootstrap.user-password=${BOOTSTRAP_USER_PASSWORD:}
app.bootstrap.seller-password=${BOOTSTRAP_SELLER_PASSWORD:}
app.bootstrap.admin-password=${BOOTSTRAP_ADMIN_PASSWORD:}
