-- =========================================================
-- V1__init_schema.sql  (Clean Flyway Baseline)
-- =========================================================

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    username VARCHAR(50) NOT NULL
);

CREATE TABLE roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) CHECK (role_name IN ('ROLE_USER','ROLE_SELLER','ROLE_ADMIN'))
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_userrole_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_userrole_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    pincode VARCHAR(20) NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    special_price DOUBLE PRECISION NOT NULL,
    discount DOUBLE PRECISION NOT NULL,
    quantity INT,
    image VARCHAR(255),
    category_id BIGINT,
    seller_id BIGINT,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES users(user_id)
);

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_price DOUBLE PRECISION,
    user_id BIGINT,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount DOUBLE PRECISION NOT NULL,
    product_price DOUBLE PRECISION NOT NULL,
    quantity INT,
    cart_id BIGINT,
    product_id BIGINT,
    CONSTRAINT fk_cartitem_cart FOREIGN KEY (cart_id) REFERENCES carts(cart_id),
    CONSTRAINT fk_cartitem_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method VARCHAR(255) NOT NULL,
    pg_name VARCHAR(255),
    pg_payment_id VARCHAR(255),
    pg_response_message VARCHAR(255),
    pg_status VARCHAR(255)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    order_date DATE,
    order_status VARCHAR(255),
    total_amount DOUBLE PRECISION,
    address_id BIGINT,
    payment_id BIGINT,
    CONSTRAINT fk_orders_address FOREIGN KEY (address_id) REFERENCES addresses(address_id),
    CONSTRAINT fk_orders_payment FOREIGN KEY (payment_id) REFERENCES payments(payment_id)
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount DOUBLE PRECISION NOT NULL,
    ordered_product_price DOUBLE PRECISION NOT NULL,
    quantity INT,
    order_id BIGINT,
    product_id BIGINT,
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);
